apiVersion: demo.codefresh.io/v1alpha1
kind: VirtualArgoCD
metadata:
  name: customer1
spec:
  argocd:
    values: 
      ingress:
        enabled: true
        annotations: 
          cert-manager.io/cluster-issuer: letsencrypt-production-issuer
        ingressClassName: "nginx"
        hostname: "argo-cd-customer1.joseph.wien"
        path: /
        pathType: Prefix
        tls: true
